---

- name: Create configuration directories
  file: name={{ item }} state=directory recurse=yes
  with_items:
    - /etc/zookeeper
    - /usr/local/etc/zookeeper/conf_local
    - /etc/mesos
    - /etc/mesos-master
    - /etc/marathon/conf

- name: Configure zookeeper
  template: src=templates/{{ item.tmpl }} dest={{ item.dest }}
  with_items:
    - { tmpl: etc-zookeeper-conf-myid.j2, dest: /usr/local/etc/zookeeper/conf_local/myid }
    - { tmpl: etc-zookeeper-conf-zoo.cfg.j2, dest: /usr/local/etc/zookeeper/conf_local/zoo.cfg }
  notify:
    - Reload Zookeeper

- name: Link zookeeper defaults
  file: path=/usr/local/etc/zookeeper/conf_local/{{ item }} src=/etc/zookeeper/conf_example/{{ item }} state=link force=yes
  with_items:
    - configuration.xsl
    - environment
    - log4j.properties
  notify:
    - Reload Zookeeper

- name: Install zookeeper-conf alternatives
  alternatives: link=/etc/zookeeper/conf name=zookeeper-conf path=/usr/local/etc/zookeeper/conf_local
  notify:
    - Reload Zookeeper

- name: Create marathon configs
  template: src=templates/{{ item.tmpl }} dest={{ item.dest }}
  with_items:
    - { tmpl: etc-marathon-conf-hostname.j2, dest: /etc/marathon/conf/hostname }
    - { tmpl: etc-marathon-conf-master.j2, dest: /etc/marathon/conf/master }
    - { tmpl: etc-marathon-conf-zk.j2, dest: /etc/marathon/conf/zk }
  notify:
    - Reload Mesos

- name: Install Components
  apt: name={{ item }} install_recommends=no
  with_items:
    - marathon
    - mesos
    - zookeeperd

- name: Start Marathon
  service: name=marathon state=started enabled=yes

- name: Wait for marathon
  wait_for: host={{ server_ip }} port=8080 delay=10

- name: Configure mesos master
  template: src=templates/{{ item.tmpl }} dest={{ item.dest }}
  with_items:
    - { tmpl: etc-mesos-zk.j2, dest: /etc/mesos/zk }
    - { tmpl: etc-mesos-master-ip.j2, dest: /etc/mesos-master/ip }
    - { tmpl: etc-mesos-master-hostname.j2, dest: /etc/mesos-master/hostname }
    - { tmpl: etc-mesos-master-quorum.j2, dest: /etc/mesos-master/quorum }
  notify:
    - Reload Mesos

- name: Cleanup mesos configuration directories
  file: path={{ item }} state=absent
  with_items:
    - /etc/mesos/zk.dpkg-dist
    - /etc/mesos-master/quorum.dpkg-dist

- name: Start Zookeeper
  service: name=zookeeper state=started enabled=yes

- name: Wait for zookeeper
  wait_for: port=2181 delay=10

- name: Start Mesos master
  service: name=mesos-master state=started enabled=yes

- name: Wait for mesos-master
  wait_for: host={{ server_ip }} port=5050 delay=10

- name: Disable Mesos slave
  service: name=mesos-slave state=stopped enabled=no
