---

- name: Create configuration directories
  file: name={{ item }} state=directory recurse=yes
  with_items:
    - /etc/mesos
    - /etc/mesos-slave

- name: Configure components
  template: src=templates/{{ item.tmpl }} dest={{ item.dest }}
  with_items:
    - { tmpl: etc-mesos-zk.j2, dest: /etc/mesos/zk }
    - { tmpl: etc-mesos-slave-ip.j2, dest: /etc/mesos-slave/ip }
    - { tmpl: etc-mesos-slave-hostname.j2, dest: /etc/mesos-slave/hostname }

- name: Install packages
  apt: name={{ item }} install_recommends=no
  with_items:
    - mesos

- name: Start Components
  service: name={{ item }} state=started enabled=yes
  with_items:
    - mesos-slave

- name: Disable Mesos master and zookeeper
  service: name={{ item }} state=stopped enabled=no
  with_items:
    - mesos-master
