---

- hosts:
    - mesos_masters
    - mesos_slaves
  become: true
  roles:
    - common

- hosts: mesos_masters
  become: true
  roles:
    - mesos-master

- hosts: mesos_slaves
  become: true
  roles:
    - mesos-slave
